version: '3.8'

services:
  neo4j:
    image: neo4j:${IMAGE_TAG}
    build:
      context: ../
      dockerfile: docker/Dockerfile.neo4j

  neo4j-db:
    container_name: Neo4j-db
    image: neo4j:${IMAGE_TAG}
    volumes:
      - ../opt/neo4j/plugins:/db/plugins   # location for .jar to use with APOC library
    ports:
      - "7474:7474"   # web client
      - "7687:7687"   # db default port (use code to access db via bolt protocol)
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      # - NEO4J_server_memory_heap_initial_size=512m
      # - NEO4J_server_memory_heap_max_size=4G
      # - NEO4J_initial_dbms_default_database=neo4j
      - NEO4J_PLUGINS=["apoc"] 
      - NEO4J_AUTH=${NEO4J_DATABASE_USERNAME-neo4j}/${NEO4J_DATABASE_PASSWORD:-test@!123}
    restart: on-failure
    networks:
      - kg_kf_network
    # command: bash -c "
    #     echo ${NEO4J_DATABASE_USERNAME}/${NEO4J_DATABASE_PASSWORD}
    #  "

networks:
  kg_kf_network:
